# HTTP-Server settings
server:
  port: 8080
    
spring:
  jackson:
    serialization:
      indent-output: true    
  thymeleaf:
    mode: HTML
      
logging:
  level:
    org: warn 
    org.elasticsearch: info
    de.arp:  debug
  pattern:
    console: "%-5level %d{yyyy-MM-dd HH:mm:ss} %logger{36} - %msg%n"

henni:
    appSecret: 7462dff391dfa35dee19c8088442ccdb
    verifyToken: retgdkfjsjklsklj34qdfs
    pageAccessToken: EAAEXd02OnC8BAOmGcuWBMp0WJFILrLUdYOgM9pZAiQcIumf6lUcuMr0yXRm5a9ANuBDYpHd5p9s3RtSfaUOAPxsMOsCqJWEl80NicaVmmE30JiCBdcjT0QLo5HXVxBsVVZC7sICZB1RYg39w26HiPZAr9gRNF7ORCvZCzpNcmUgZDZD

